var blackMetalWords = [
  "black",
  "Beyond",
  "vast",
  "gulf",
  "chasm",
  "crack",
  "creak",
  "pounding",
  "throbbing",
  "pulvarize",
  "bashing",
  "smash",
  "dungeon",
  "obliterate",
  "burial",
  "shatter",
  "scatter",
  "atone",
  "emperor",
  "wizard",
  "Cthulhu",
  "Nyarlathotep",
  "Azathoth",
  "Dunwich",
  "horror",
  "terror",
  "cannibal",
  "call",
  "mad",
  "fury",
  "clench",
  "writhe",
  "squirm",
  "hysteria",
  "villain",
  "supernatural",
  "consume",
  "maw",
  "gore",
  "scour",
  "scowl",
  "burbling",
  "frothing",
  "worm",
  "vermin",
  "rancid",
  "beware",
  "malice",
  "cacophony",
  "bones",
  "skeleton",
  "swarm",
  "blastbeat",
  "exorcism",
  "night",
  "shrieking",
  "descend",
  "ghosts",
  "streak",
  "tombstone",
  "epitaph",
  "ghouls",
  "inferno",
  "evermore",
  "forevermore",
  "Dante",
  "folklore",
  "woods",
  "the",
  "be",
  "to",
  "of",
  "and",
  "a",
  "in",
  "that",
  "have",
  "I",
  "it",
  "for",
  "not",
  "on",
  "with",
  "he",
  "as",
  "you",
  "do",
  "at",
  "this",
  "but",
  "his",
  "by",
  "from",
  "they",
  "we",
  "say",
  "her",
  "she",
  "or",
  "an",
  "will",
  "my",
  "one",
  "all",
  "would",
  "there",
  "their",
  "what",
  "so",
  "up",
  "out",
  "if",
  "about",
  "who",
  "get",
  "which",
  "go",
  "me",
  "when",
  "make",
  "can",
  "like",
  "time",
  "no",
  "just",
  "him",
  "know",
  "take",
  "people",
  "into",
  "year",
  "your",
  "good",
  "some",
  "could",
  "them",
  "see",
  "other",
  "than",
  "then",
  "now",
  "look",
  "only",
  "come",
  "its",
  "over",
  "think",
  "also",
  "back",
  "after",
  "use",
  "two",
  "how",
  "our",
  "work",
  "first",
  "well",
  "way",
  "even",
  "new",
  "want",
  "because",
  "any",
  "these",
  "give",
  "day",
  "most",
  "us",
  "undead",
  "undying",
  "torment",
  "burn",
  "pyre",
  "sigh",
  "dread",
  "dreadful",
  "Grim Reaper",
  "Beelzebub",
  "shrine",
  "hearth",
  "glacier",
  "Fjord",
  "deadly",
  "envy",
  "pagan",
  "Thor",
  "Odin",
  "Fenrir",
  "Asgard",
  "Valhalla",
  "Bergen",
  "Oslo",
  "metal",
  "fight",
  "power",
  "amps",
  "set",
  "to",
  "explode",
  "energy",
  "chime",
  "magic",
  "screams",
  "dreams",
  "and",
  "bell",
  "maniacs",
  "chaos",
  "hell",
  "pure",
  "brain",
  "hemmorrhage",
  "cure",
  "lay",
  "down",
  "steel",
  "fortune",
  "gods",
  "rock",
  "roll",
  "freaking",
  "wild",
  "code",
  "core",
  "atomic",
  "feel",
  "remorse",
  "crank",
  "deadly",
  "force",
  "stallions",
  "bareback",
  "free",
  "raw",
  "quest",
  "satan",
  "band",
  "against",
  "odds",
  "raven",
  "bane",
  "wretched",
  "eerie",
  "nightside",
  "enigma",
  "obsidian",
  "leather",
  "casting",
  "spell",
  "screams",
  "nuclear",
  "hounds",
  "sound",
  "falls",
  "cloaks",
  "impenetrable",
  "darkness",
  "chill",
  "rises",
  "soil",
  "from",
  "contaminates",
  "suddenly",
  "life",
  "has",
  "new",
  "meaning",
  "figure",
  "there",
  "hilltop",
  "evil",
  "withered",
  "gloomy",
  "soul",
  "cold",
  "ice",
  "philosphy",
  "because",
  "power",
  "winter",
  "shall",
  "shatter",
  "broken",
  "oblivion",
  "never",
  "wonder",
  "light",
  "pain",
  "ritual",
  "serpent",
  "solitude",
  "occult",
  "necro",
  "blasphemy",
  "mourn",
  "haunting",
  "lurk",
  "Prometheus",
  "vortex",
  "omen",
  "portend",
  "spectral",
  "Leviathan",
  "profane",
  "unearth",
  "shrouded",
  "plunge",
  "dissonance",
  "iconoclast",
  "eclipse",
  "nightside",
  "pestilence",
  "desecrate",
  "martyr",
  "Nihil",
  "obscene",
  "obscure",
  "chalice",
  "lament",
  "rotting",
  "sinister",
  "miasma",
  "vanquish",
  "chasm",
  "unseen",
  "lasts",
  "dreadful",
  "rode",
  "forests",
  "old",
  "of",
  "grey",
  "freezing",
  "funeral",
  "hopelessness",
  "moon",
  "dying",
  "agony",
  "fear",
  "hatred",
  "Norway",
  "norse",
  "true",
  "nightside",
  "eclipse",
  "warfare",
  "almighty",
  "emperor",
  "into",
  "infinity",
  "thoughts",
  "shadows",
  "mountains",
  "reach",
  "awake",
  "rise",
  "wander",
  "many",
  "centuries",
  "ago",
  "under",
  "trees",
  "nature",
  "whispering",
  "warmth",
  "beyond",
  "calling",
  "gaze",
  "which",
  "grants",
  "visions",
  "nightmares",
  "escape",
  "full",
  "disciples",
  "weaker",
  "one",
  "crystal",
  "lakes",
  "darkest",
  "flame",
  "temple",
  "inside",
  "eyes",
  "children",
  "grind",
  "wherever",
  "reign",
  "fear",
  "lands",
  "phantoms",
  "wastelands",
  "grow",
  "moments",
  "haunt",
  "blasphemy",
  "purgatory",
  "sorrow",
  "speak",
  "burns",
  "skin",
  "grievance",
  "bloodred",
  "lights",
  "hearts",
  "thunders",
  "lightning",
  "strike",
  "cracks",
  "sky",
  "fantasies",
  "throne",
  "so",
  "forever",
  "crawl",
  "purity",
  "cosmic",
  "creations",
  "lit",
  "reflected",
  "drowning",
  "unlimited",
  "bark",
  "howl",
  "snarl",
  "depressive",
  "atmosphere",
  "eternally",
  "eternity",
  "never",
  "loathing",
  "mortis",
  "immortal",
  "mortal",
  "voyage",
  "vision",
  "predictions",
  "teardrops",
  "ground",
  "sarcophagus",
  "disappear",
  "burning",
  "skin",
  "flesh",
  "plunging",
  "twisting",
  "somniferous",
  "candles",
  "rotten",
  "unclean",
  "sacrifice",
  "journey",
  "darkside",
  "realm",
  "methane",
  "dust",
  "vast",
  "homeland",
  "ship",
  "morbid",
  "hillsides",
  "ancient",
  "cultures",
  "kneel",
  "altar",
  "autumn",
  "avarice",
  "lost",
  "grave",
  "graveyard",
  "cemetary",
  "tomb",
  "mausoleum",
  "wound",
  "licking",
  "wounds",
  "allergic",
  "rotting",
  "rot",
  "spit",
  "mouth",
  "maw",
  "gaping",
  "empty",
  "nothingness",
  "kill",
  "revenge",
  "avenge",
  "view",
  "crucifix",
  "horizon",
  "submerge",
  "glass",
  "white",
  "nocturnal",
  "decomposed",
  "decomposing",
  "coffin",
  "ashes",
  "sepulchural",
  "macabre",
  "symbol",
  "silently",
  "silence",
  "watchtower",
  "humanoid",
  "glance",
  "the other side",
  "blaze",
  "blazing",
  "northern",
  "coyotes",
  "red",
  "strong",
  "Baphomet",
  "clan",
  "ceremonial",
  "disciples",
  "sparks",
  "diabolical",
  "beast",
  "living",
  "desecrated",
  "horns",
  "goat",
  "lamb",
  "gazed",
  "dawn",
  "cleansed",
  "cursed",
  "triumph",
  "weeping",
  "witchcraft",
  "warlock",
  "enshrined",
  "spectre",
  "frost",
  "boiling",
  "castle",
  "Faust",
  "Belial",
  "forth",
  "writings",
  "scrolls",
  "Dreamking",
  "Tombworld",
  "paragon",
  "oath",
  "breaker",
  "rusty",
  "rust",
  "rusting",
  "edges",
  "blackened",
  "shroud",
  "shrouded",
  "sharp",
  "snake",
  "armageddon",
  "apocalypse",
  "benighted",
  "Ragnarok",
  "gnash",
  "Heimdallr",
  "Frigg",
  "Týr",
  "Loki",
  "blood",
  "conspiracy",
  "fading",
  "asleep",
  "stars",
  "scattered",
  "awaiting",
  "hunger",
  "starvation",
  "haze",
  "elder",
  "dustclouds",
  "die",
  "Sythanagon",
  "summon",
  "emerge",
  "ablaze",
  "limbs",
  "Apharamons",
  "spear",
  "scalp",
  "bonecrushing",
  "poisoned",
  "until",
  "yearn",
  "beckon",
  "flicker",
  "limit",
  "mirror",
  "cut",
  "through",
  "beneath",
  "distant",
  "baptised",
  "naked",
  "tortured",
  "ugliness",
  "unshaken",
  "same",
  "knowing",
  "crusted",
  "sealed",
  "the one",
  "him",
  "he",
  "soon",
  "oppressed",
  "plague",
  "thorns",
  "tyrant",
  "blight",
  "angel of death",
  "greed",
  "wrath",
  "sloth",
  "gluttony",
  "pride",
  "Mammon",
  "Belphegor",
  "Asmodeus",
  "Abaddon",
  "exorcism",
  "hierarchy",
  "servant",
  "subterranean",
  "hunt",
  "lantern",
  "cape",
  "orb",
  "grimoire",
  "gothic",
  "grim",
  "ghastly",
  "grisly",
  "harsh",
  "ominous",
  "somber",
  "ferocious",
  "resolute",
  "merciless",
  "morose",
  "unrelenting",
  "unyielding",
  "hideous",
  "terrible",
  "sullen",
];

var indieWords = [
  "dove",
  "Bacchanal",
  "reverie",
  "futile",
  "bride",
  "brother",
  "sister",
  "held",
  "cornucopia",
  "lather",
  "lathe",
  "satin",
  "chakra",
  "hawk",
  "bread",
  "close",
  "grow",
  "stretch",
  "yawn",
  "silvery",
  "streams",
  "sacred",
  "spoken",
  "perceive",
  "broken",
  "furrow",
  "burrow",
  "warren",
  "seeds",
  "planting",
  "ambient",
  "atmosphere",
  "safe",
  "warm",
  "fountain",
  "shrine",
  "stranded",
  "innocent",
  "revelation",
  "blister",
  "where is my",
  "way out",
  "hum",
  "woodwinds",
  "orchestral",
  "throbbing",
  "brass",
  "guitar",
  "flute",
  "exorcismic",
  "aeroplane",
  "sea",
  "tulips",
  "peony",
  "sunflower",
  "seeds",
  "rose",
  "marigold",
  "snapdragon",
  "lavender",
  "daffodil",
  "moth",
  "dragonfly",
  "hyacinth",
  "transfiguration",
  "clap",
  "hands",
  "transubstantiation",
  "dowry",
  "pastoral",
  "kitten",
  "mewing",
  "lilac",
  "stitch",
  "hoop",
  "blowing",
  "brine",
  "tumbleweed",
  "love",
  "summertime",
  "regret",
  "days",
  "owl",
  "hummingbird",
  "summer",
  "emptiness",
  "crow",
  "swim",
  "swallow",
  "swan",
  "falling",
  "to",
  "never",
  "forget",
  "safety",
  "if",
  "am",
  "alive",
  "this",
  "time",
  "next",
  "year",
  "share",
  "good",
  "mine",
  "applied",
  "thoughts",
  "trees",
  "great",
  "impossible",
  "parade",
  "hills",
  "band",
  "sound",
  "made",
  "fell",
  "drove",
  "things",
  "know",
  "clothes",
  "sold",
  "our",
  "state",
  "mistakes",
  "mind",
  "came",
  "pyre",
  "take",
  "recreate",
  "grow",
  "garden",
  "mindset",
  "find",
  "New York",
  "van",
  "with my friend",
  "I don't mind",
  "white coat",
  "bury",
  "gnawing",
  "telephone",
  "pray",
  "suspend",
  "lead",
  "water",
  "mercy",
  "clouds",
  "he",
  "almost",
  "breathed",
  "crept",
  "over",
  "deeply",
  "resolute",
  "weeds",
  "pulled",
  "morning",
  "meadowlark",
  "home",
  "hearth",
  "Williamsburg",
  "Portland",
  "hiking",
  "sailed",
  "away",
  "malleable",
  "clay",
  "nautical",
  "say",
  "fades",
  "recall",
  "caravel",
  "wicker",
  "beetle",
  "shell",
  "four",
  "fine",
  "sails",
  "funny",
  "little",
  "bridges",
  "balloons",
  "dirigibles",
  "irritable",
  "canaries",
  "pine",
  "birch",
  "calm",
  "tranquil",
  "brace",
  "thimble",
  "touch",
  "hearts",
  "thimble",
  "slept",
  "sprout",
  "bean",
  "the difference between",
  "king",
  "outside",
  "go",
  "should",
  "could",
  "will",
  "break",
  "bread",
  "seamless",
  "though",
  "sigh",
  "grotesque",
  "animal",
  "completely",
  "softly",
  "sighing",
  "sun",
  "bothered",
  "appreciate",
  "cute",
  "girl",
  "festival",
  "explain",
  "embarassing",
  "disaster",
  "performance",
  "mousy",
  "predictable",
  "mythologizing",
  "perceive",
  "radiance",
  "wonderful",
  "tell",
  "lifting",
  "goodness",
  "young",
  "were",
  "king",
  "carrot",
  "tower",
  "tumbling",
  "seas",
  "holy",
  "in",
  "rattlesnakes",
  "fell",
  "around",
  "feet",
  "room",
  "afternoon",
  "knew",
  "could",
  "above",
  "you",
  "how",
  "sank",
  "into",
  "your",
  "soul",
  "place",
  "go",
  "neutral",
  "milk",
  "hotel",
  "valentine",
  "Montreal",
  "reborn",
  "aurora borealis",
  "knife",
  "shoulders",
  "garbage",
  "speaking",
  "die",
  "dare",
  "try",
  "easy",
  "rest",
  "beyond",
  "bed",
  "blessed",
  "sustained",
  "harvest",
  "sown",
  "dulling",
  "service",
  "heart",
  "alone",
  "life-giver",
  "intend",
  "valley",
  "green",
  "luck",
  "pluck",
  "daisy",
  "'til",
  "may",
  "honey",
  "port",
  "fog",
  "lays",
  "snow",
  "frog",
  "Roanoke",
  "courting",
  "foot",
  "croaks",
  "river",
  "light",
  "c'mon",
  "livelong",
  "weight",
  "fate",
  "mirror",
  "appear",
  "courtyard",
  "Daddy Longlegs",
  "stay",
  "dance",
  "skirt",
  "mounting",
  "grace",
  "career",
  "handsome",
  "brassiere",
  "floating",
  "dust",
  "heaven",
  "save",
  "glitter",
  "amends",
  "park",
  "bouquet",
  "bottle of wine",
  "arms",
  "upstairs",
  "living room",
  "bedroom",
  "kitchen",
  "foyer",
  "buoys",
  "excellent",
  "proud",
  "glow",
  "hello",
  "country",
  "beginning",
  "conclusion",
  "upright",
  "easterly",
  "duration",
  "remain",
  "bump",
  "log",
  "pirouette",
  "intentions",
  "company",
  "slack",
  "the",
  "be",
  "to",
  "of",
  "and",
  "a",
  "in",
  "that",
  "have",
  "I",
  "it",
  "for",
  "not",
  "on",
  "with",
  "he",
  "as",
  "you",
  "do",
  "at",
  "this",
  "but",
  "his",
  "by",
  "from",
  "they",
  "we",
  "say",
  "her",
  "she",
  "or",
  "an",
  "will",
  "my",
  "one",
  "all",
  "would",
  "there",
  "their",
  "what",
  "so",
  "up",
  "out",
  "if",
  "about",
  "who",
  "get",
  "which",
  "go",
  "me",
  "when",
  "make",
  "can",
  "like",
  "time",
  "no",
  "just",
  "him",
  "know",
  "take",
  "people",
  "into",
  "year",
  "your",
  "good",
  "some",
  "could",
  "them",
  "see",
  "other",
  "than",
  "then",
  "now",
  "look",
  "only",
  "come",
  "its",
  "over",
  "think",
  "also",
  "back",
  "after",
  "use",
  "two",
  "how",
  "our",
  "work",
  "first",
  "well",
  "way",
  "even",
  "new",
  "want",
  "because",
  "any",
  "these",
  "give",
  "tomatoes",
  "radio wires",
  "retire",
  "sheets",
  "organ",
  "day",
  "most",
  "us",
  "deceived",
  "face",
  "phosphorescence",
  "essence",
  "regress",
  "birth",
  "borne",
  "sailors",
  "pier",
  "abide",
  "capsize",
  "recall",
  "depth",
  "coast",
  "masts",
  "arid",
  "yoke",
  "waves",
  "silk",
  "pearl",
  "woman",
  "rift",
  "spanning",
  "distant",
  "anecdotes",
  "scouts",
  "sending",
  "anticipate",
  "jar",
  "loom",
  "torpor",
  "temporal",
  "San Francisco",
  "folds",
  "branches",
  "twigs",
  "leaves",
  "spilling",
  "speak",
  "sideboards",
  "creak",
  "creek",
  "trenches",
  "remembering",
  "parting",
  "carrying",
  "grieving",
  "kettle",
  "spotted",
  "sanded",
  "beveled",
  "monument",
  "part 2",
  "unrecorded",
  "circling",
  "beautiful",
  "flash",
  "screen",
  "blink",
  "soft",
  "sweet",
  "with me",
  "close",
  "patch",
  "grass",
  "fields",
  "colonnades",
  "surmised",
  "flouresce",
  "dwell",
  "alderman",
  "decipher",
  "goose",
  "eggshells",
  "somebody",
  "vamoose",
  "coals",
  "refuse",
  "flock",
  "long ago",
  "notice",
  "ascension",
  "fleet",
  "simulacra",
  "lapsed",
  "lash",
  "barely",
  "pristine",
  "chalet",
  "chateau",
  "garden",
  "fellow",
  "highlands",
  "tempest",
  "tempestuous",
  "fidelity",
  "vulpine",
  "engenders",
  "renew",
  "deity",
  "bleeding",
  "babe",
  "peerless",
  "motivate",
  "chariot",
  "sweetly",
  "displays",
  "pulleys",
  "weights",
  "sparkle",
  "lover",
  "hands",
  "across",
  "toes",
  "take off",
  "placing",
  "notches",
  "spine",
  "dialogue",
  "oblique",
  "prairie",
  "shine",
  "voices",
  "roads",
  "tomorrow",
  "extraordinary",
  "questions",
  "answers",
  "wonder",
  "echoes",
  "melodies",
  "nectar",
  "sunset",
  "sunrise",
];

var rapWords = [
  "yeah",
  "flow",
  "grimey",
  "spree",
  "soul",
  "ill",
  "stoop",
  "lick",
  "skip",
  "loose",
  "code",
  "mixtape",
  "desperados",
  "boom bap",
  "twister",
  "fly",
  "testify",
  "lyrics",
  "mic",
  "blades",
  "fiends",
  "Cheetos",
  "Doritos",
  "Fritos",
  "index",
  "techs",
  "trippin'",
  "fine",
  "flavor",
  "rack",
  "satin",
  "ladies and gentlemen",
  "finer things",
  "live",
  "laid back",
  "Barry White",
  "Marvin Gaye",
  "headshot",
  "exaggeration",
  "buttery",
  "plates",
  "chakra",
  "Clint Eastwood",
  "hawk",
  "nerve",
  "stage",
  "vaudeville",
  "most",
  "headquarters",
  "barcode",
  "dope",
  "baggy",
  "swag",
  "rubies",
  "pray",
  "free",
  "Newport",
  "loot",
  "switch",
  "perimeter",
  "consume",
  "bread",
  "drop",
  "name",
  "fit",
  "style",
  "stylin'",
  "stylish",
  "t-shirt",
  "Givenchy",
  "Reebok's",
  "Adidas",
  "Lakers",
  "Bulls",
  "class",
  "stash",
  "competitor",
  "expertise",
  "mogul",
  "flambé",
  "chop",
  "screwed",
  "Benihana",
  "known",
  "been",
  "be",
  "stereo",
  "candid",
  "G",
  "meal",
  "jerk",
  "hook",
  "quadruple",
  "double",
  "pills",
  "told ya",
  "this is it",
  "tact",
  "piano",
  "rum",
  "ice cream",
  "dream",
  "triple",
  "low key",
  "silly",
  "egad",
  "head",
  "rock it",
  "rocket",
  "beware",
  "justice",
  "clever",
  "wise crack",
  "blocka",
  "revelation",
  "wisdom",
  "future",
  "100",
  "Sosa",
  "Raris",
  "free",
  "percussion",
  "whip",
  "Marilyn Monroe",
  "El Chapo",
  "Donald Trump",
  "Jay-Z",
  "Biggie",
  "Tupac",
  "Andre",
  "3 Stacks",
  "300",
  "7-11",
  "corner store",
  "Angelina Jolie",
  "Paris Hilton",
  "Diddy",
  "Serena Williams",
  "Denzel Washington",
  "Brad Pitt",
  "Al Pacino",
  "Hugh Hefner",
  "playboy",
  "Oprah Winfrey",
  "emcees",
  "fools",
  "DJ",
  "the",
  "be",
  "to",
  "of",
  "and",
  "a",
  "in",
  "that",
  "have",
  "I",
  "it",
  "for",
  "not",
  "on",
  "with",
  "he",
  "as",
  "you",
  "do",
  "at",
  "this",
  "but",
  "his",
  "by",
  "from",
  "they",
  "we",
  "say",
  "her",
  "she",
  "or",
  "an",
  "will",
  "my",
  "one",
  "all",
  "would",
  "there",
  "their",
  "what",
  "so",
  "up",
  "out",
  "if",
  "about",
  "who",
  "get",
  "which",
  "go",
  "me",
  "when",
  "make",
  "can",
  "like",
  "time",
  "no",
  "just",
  "him",
  "know",
  "take",
  "people",
  "into",
  "year",
  "your",
  "good",
  "some",
  "could",
  "them",
  "see",
  "other",
  "than",
  "then",
  "now",
  "look",
  "only",
  "come",
  "its",
  "over",
  "think",
  "also",
  "back",
  "after",
  "use",
  "two",
  "how",
  "our",
  "work",
  "first",
  "well",
  "way",
  "even",
  "new",
  "want",
  "because",
  "any",
  "these",
  "give",
  "day",
  "most",
  "us",
  "it",
  "was",
  "all",
  "yea",
  "they",
  "on some",
  "dream",
  "game",
  "extortion",
  "word up",
  "magazine",
  "salt",
  "pepa",
  "heavy-d",
  "limousine",
  "daughter",
  "baby baby",
  "Versace",
  "illuminati",
  "love",
  "audi",
  "plug",
  "John Gotti",
  "dozen",
  "shoes",
  "shirt",
  "silk",
  "bustin'",
  "rumble",
  "police",
  "constantly",
  "money",
  "ambitions",
  "ridah",
  "battlefield",
  "scars",
  "rap",
  "rugged",
  "rough",
  "addressin'",
  "soldier",
  "ear",
  "smokin'",
  "bomb",
  "crucial",
  "Gucci flip flops",
  "Gucci",
  "huslin'",
  "party",
  "house",
  "tonight",
  "street",
  "pay",
  "mission",
  "ticket",
  "competition",
  "blitzed",
  "stressin",
  "Lebron",
  "Nikes",
  "bad",
  "thick",
  "bands",
  "countin'",
  "should've",
  "push",
  "real",
  "swag",
  "everybody",
  "Xanny",
  "raindrop",
  "drop-top",
  "cookie",
  "hotpox",
  "thot",
  "trigger",
  "bougie",
  "trust",
  "hundred",
  "rounds",
  "is",
  "ain't",
  "finna",
  "Uzi",
  "Coupe",
  "hop",
  "company",
  "dab",
  "Uber",
  "iPhone",
  "racks",
  "dat",
  "fat",
  "international",
  "drag race",
  "ruthless",
  "savage",
  "outer space",
  "shooters",
  "ice",
  "diamonds",
  "gold",
  "gold chain",
  "grillz",
  "clout",
  "check",
  "sicko",
  "mode",
  "dawg",
  "Louis",
  "prolly",
  "tried",
  "show",
  "nothin'",
  "jump",
  "pick and roll",
  "gone",
  "made",
  "here",
  "out",
  "hoppin'",
  "poppin'",
  "choppin'",
  "Remy",
  "pull",
  "up",
  "lockdown",
  "lock",
  "mixes",
  "mixtape",
  "mix",
  "jeweler",
  "jewelry",
  "necklace",
  "rings",
  "crackers",
  "different",
  "colors",
  "trap",
  "retreat",
  "keeps",
  "exes",
  "produced",
  "deep",
  "pop",
  "pool",
  "FaceTime",
  "someone",
  "moon",
  "man",
  "mansion",
  "12 car garage",
  "boy",
  "Sprite",
  "dirty",
  "wild",
  "night",
  "polite",
  "word up",
  "son",
  "killers",
  "billers",
  "open",
  "for real",
  "no doubt",
  "stuck",
  "realness",
  "infamous",
  "heard",
  "murderers",
  "equipped",
  "beware",
  "shots",
  "share",
  "crime",
  "family",
  "profile",
  "pose",
  "stab",
  "land",
  "gunning",
  "shook",
  "crews",
  "runnin'",
  "laced",
  "bullet",
  "holes",
  "speak",
  "army",
  "team",
  "breathing",
  "guarantee",
  "major",
  "featherweight",
  "deceased",
  "Queens",
  "tight",
  "situation",
  "rhyme",
  "crooks",
  "halfway",
  "funds",
  "incarceration",
  "heat",
  "packin'",
  "projects",
  "mentality",
  "kid",
  "recognition",
  "recognize",
  "spit",
  "spittin'",
  "wet",
  "certified freak",
  "certified",
  "chain",
  "Henny",
  "cobra",
  "followers",
  "God",
  "devil",
  "tryin'",
  "witness",
  "riches",
  "6 feet under",
  "Lord",
  "ball",
  "Southside",
  "Chiraq",
  "Staten Island",
  "Brooklyn",
  "Bed Stuy",
  "breathin'",
  "thirsty",
  "jungle",
  "cousin",
  "funky",
  "rhythm",
  "forever",
  "laughin'",
  "composition",
  "pain",
  "Scarface",
  "Tony Montana",
  "Kobe",
  "Lebron",
  "Jordan",
  "champs",
  "reminiscin'",
  "flipped",
  "Houston",
  "Atlanta",
  "buildin'",
  "lobby",
  "squeeze",
  "chamber",
  "back-to-back",
  "triggers",
  "goner",
  "stash",
  "customers",
  "measuring",
  "vacation",
  "Dubai",
  "New York",
  "yo",
  "ayo",
  "get the",
  "run the",
  "state of mind",
  "hustle",
  "hustlers",
  "hustlin",
  "Moët",
  "Dom Perignon",
  "bubbly",
  "bottleservice",
  "Buddha",
  "Jesus",
  "strays",
  "cops",
  "rocks",
  "tape",
  "mixtape",
  "Capone",
  "smooth",
  "Miami",
  "inhale",
  "backtrack",
  "bark",
  "hooked",
  "homies",
  "woes",
  "double",
  "triple",
  "MJ",
  "pad",
  "static",
  "flexin'",
  "MTV",
  "domino",
  "LA",
  "grade",
  "chronic",
  "phat",
  "drove",
  "coastin'",
  "chillin'",
  "vibin'",
  "pop",
  "high beams",
  "Beamer",
  "boy",
  "Bugatti",
  "Lambourghini",
  "opportunity",
  "spaghetti",
  "Mama",
  "heavy",
  "arms",
  "bombs",
  "wocky",
  "purple",
  "pusher",
  "she said",
  "he said",
  "storytellin'",
  "da art of",
  "stacks",
  "racks",
  "moonwalk",
  "money",
  "city",
  "zoo",
  "Sun Ra",
  "Coltrane",
  "destiny",
  "equation",
  "official",
  "powerful",
  "operation",
  "God",
  "shoo-in",
  "mask",
  "unpredictable",
  "",
];

var countryWords = [
  "baby",
  "valley",
  "closing time",
  "last call",
  "pigeon",
  "suit and tie",
  "hellhound",
  "saddle",
  "memory",
  "mare",
  "Bessie",
  "cow",
  "cowpoke",
  "city slicker",
  "out of town",
  "vista",
  "off-roading",
  "beggin'",
  "ma'am",
  "sir",
  "rope",
  "settling",
  "big fat",
  "heart",
  "ride",
  "pony",
  "cattle",
  "stealing",
  "robbing",
  "sidekick",
  "Jesse James",
  "ranger",
  "shotgun",
  "burning",
  "cry",
  "heartache",
  "old",
  "ole",
  "sho-nuff",
  "boys",
  "kinda",
  "some",
  "lock",
  "lyin'",
  "fool",
  "breeze",
  "ranch",
  "gallows",
  "rope",
  "rawhide",
  "sierra",
  "Nevada",
  "siesta",
  "bars",
  "blues",
  "away",
  "harmonica",
  "Florida",
  "sheriff",
  "deputy",
  "marshall",
  "gallon",
  "preacher",
  "glory",
  "mercy",
  "judge",
  "pen",
  "mineshaft",
  "honky tonk",
  "sugar",
  "pleasures",
  "fellers",
  "seek not",
  "dreary",
  "coal",
  "railroad",
  "hidey ho",
  "cigars",
  "cigarette",
  "pipe",
  "smoked",
  "whistle",
  "desperado",
  "Tuscaloosa",
  "bucolic",
  "four wheeler",
  "denim",
  "cowboy hat",
  "jail",
  "moanin'",
  "mojo",
  "rifle",
  "graveyard",
  "chicago",
  "hobo",
  "wailin'",
  "sweat",
  "lonesome",
  "whiskey",
  "holler",
  "hurtin'",
  "pistol",
  "workin'",
  "screamin'",
  "chain",
  "rollin'",
  "junker",
  "hound",
  "hound-dog",
  "bad",
  "sinner",
  "dog",
  "hound",
  "hound-dog",
  "bad",
  "sinner",
  "ramble",
  "tangle",
  "sloppy",
  "chicken",
  "run",
  "voodoo",
  "delta",
  "dust",
  "slidin'",
  "blind",
  "beggin'",
  "bottle",
  "crawl",
  "sorrow",
  "scratch",
  "snake",
  "worry",
  "sugar",
  "bricks",
  "kitchen",
  "drown",
  "sugar",
  "jelly",
  "goin'",
  "daddy",
  "roll",
  "jump",
  "wonder",
  "sugar",
  "jelly",
  "goin'",
  "daddy",
  "roll",
  "jump",
  "wonder",
  "devil",
  "dime",
  "sleepin'",
  "rhythm",
  "pain",
  "stranger",
  "river",
  "shout",
  "luck",
  "beggin'",
  "swing",
  "sting",
  "evil",
  "squeeze",
  "kiss",
  "beg",
  "cloud",
  "crossroads",
  "heaven",
  "fiddle",
  "catfish",
  "storm",
  "barrelhouse",
  "rider",
  "rockin'",
  "tremblin'",
  "street",
  "boots",
  "America",
  "old faithful",
  "moon",
  "deep",
  "freight",
  "load",
  "sun",
  "wander",
  "cheatin'",
  "rollin'",
  "nobody",
  "yonder",
  "stray",
  "desperation",
  "cane",
  "ride",
  "stingin'",
  "hurtin'",
  "wanderin'",
  "whiskey",
  "sweat",
  "mornin'",
  "wonderin'",
  "dog",
  "beggin'",
  "the",
  "be",
  "to",
  "of",
  "and",
  "a",
  "in",
  "that",
  "have",
  "I",
  "it",
  "for",
  "not",
  "on",
  "with",
  "he",
  "as",
  "you",
  "do",
  "at",
  "this",
  "but",
  "his",
  "by",
  "from",
  "they",
  "we",
  "say",
  "her",
  "she",
  "or",
  "an",
  "will",
  "my",
  "one",
  "all",
  "would",
  "there",
  "their",
  "what",
  "so",
  "up",
  "out",
  "if",
  "about",
  "who",
  "get",
  "which",
  "go",
  "me",
  "when",
  "make",
  "can",
  "like",
  "time",
  "no",
  "just",
  "him",
  "know",
  "take",
  "people",
  "into",
  "year",
  "your",
  "good",
  "some",
  "could",
  "them",
  "see",
  "other",
  "than",
  "then",
  "now",
  "look",
  "only",
  "come",
  "its",
  "over",
  "think",
  "also",
  "back",
  "after",
  "use",
  "two",
  "how",
  "our",
  "work",
  "first",
  "well",
  "way",
  "even",
  "new",
  "want",
  "because",
  "any",
  "these",
  "give",
  "day",
  "most",
  "us",
  "cane",
  "rhythm",
  "squeeze",
  "nobody",
  "sun",
  "deep",
  "fire",
  "cold",
  "endless",
  "tried",
  "whiskey",
  "train",
  "walkin'",
  "muddy",
  "stop",
  "feelin'",
  "red",
  "black",
  "bottle",
  "roadhouse",
  "mean",
  "dirty",
  "rock",
  "river",
  "drink",
  "luck",
  "beggin'",
  "ain't",
  "rain",
  "big",
  "honey",
  "sittin'",
  "sweet",
  "slow",
  "down",
  "hurt",
  "storm",
  "blue",
  "hallelujah",
  "was a",
  "hometown",
  "breakfast",
  "bacon",
  "eggs",
  "cowboy",
  "boots",
  "spurs",
  "big iron",
  "ballads",
  "outlaw",
  "jail cell",
  "prison",
  "Folsam",
  "San Quintan",
  "Juarez",
  "Mexico",
  "El Paso",
  "jug",
  "spoons",
  "dream",
  "train",
  "hard",
  "guitar",
  "drinkin'",
  "crossroad",
  "cold",
  "chain",
  "night",
  "singin'",
  "killin'",
  "rag",
  "wailin'",
  "trouble",
  "woman",
  "soul",
  "drownin'",
  "sky",
  "freight",
  "gambler",
  "bird",
  "midnight",
  "travelin'",
  "graveyard",
  "strollin'",
  "dust",
  "mornin'",
  "blow",
  "tired",
  "train",
  "driftin'",
  "missin'",
  "Alabama",
  "Mississippi",
  "Georgia",
  "Tennessee",
  "Virginia",
  "Kentucky",
  "Texas",
  "panhandle",
  "bad",
  "dog",
  "jones",
  "shade",
  "watchin'",
  "low",
  "belly",
  "hide",
  "clay",
  "walkin'",
  "heartache",
  "doggone",
  "laugh",
  "bell",
  "rainy",
  "sing",
  "shine",
  "goin'",
  "bone",
  "flood",
  "heaven",
  "angel",
  "wild",
  "drunk",
  "shot",
  "bad",
  "woman",
  "ride",
  "cryin'",
  "died",
  "tombstone",
  "mule",
  "desire",
  "fist",
  "holler",
  "dollar",
  "coal",
  "fast",
  "trash",
  "rooster",
  "boogie",
  "jump",
  "stomp",
  "crawlin'",
  "blues",
  "love",
  "gonna",
  "good",
  "down",
  "long",
  "night",
  "man",
  "got",
  "feel",
  "way",
  "time",
  "woman",
  "oh",
  "come",
  "ain't",
  "well",
  "lord",
  "tell",
  "know",
  "want",
  "see",
  "life",
  "call",
  "back",
  "make",
  "sweet",
  "shake",
  "old",
  "one",
  "heart",
  "need",
  "take",
  "right",
  "hard",
  "keep",
  "mean",
  "sing",
  "leave",
  "bayou",
  "tractor",
  "beer",
  "Budweiser",
  "Bud Lite",
  "feel",
  "city",
  "home",
  "rain",
  "money",
  "train",
  "poor",
  "mind",
  "miss",
  "woman",
  "morning",
  "trouble",
  "change",
  "road",
  "doin'",
  "every",
  "guitar",
  "ramblin'",
  "stand",
  "alone",
  "death",
  "before",
  "everyday",
  "watch",
  "done",
  "hurt",
  "head",
  "true",
  "dark",
  "dream",
  "better",
  "run",
  "listen",
  "hope",
  "tell",
  "believe",
  "lost",
  "jazz",
  "piano",
  "walk",
  "late",
  "friend",
  "gone",
  "father",
  "together",
  "moan",
  "tomorrow",
  "low",
  "goin'",
  "high",
  "strange",
  "born",
  "stop",
  "lovin'",
  "country",
  "hallelujah",
  "rhinestone",
  "bolo",
  "passion",
  "trust",
  "lonesome",
  "devil",
  "grave",
  "worry",
  "mama",
  "shame",
  "Nashville",
  "Memphis",
  "Austin",
  "Houston",
  "Dallas",
  "Oklahoma",
  "freedom",
  "liberty",
  "line",
  "church",
  "worship",
  "Sunday",
  "hang",
  "six shooter",
  "beans",
  "steak",
  "campfire",
  "trail",
  "lady",
  "lowlands",
  "horizon",
  "town",
  "Greyhound",
  "station",
  "blowin'",
  "poker",
  "gamblin'",
  "sorrow",
  "sorry",
  "son of a gun",
  "revolver",
];

var everything = document.querySelector("#everything");
var tabText = document.querySelector("#tab-text");
var favIcon = document.querySelector("#icon");
var descrptionLine = document.querySelector("#description");
var titleText = document.querySelector("#title-text");
var container = document.querySelector("#container");
var inputContainer = document.querySelector("#input-container");
var genreSelect = document.querySelector("#genre");
var numberInput = document.querySelector("#number-of-words");
var submitButton = document.querySelector("#submit-button");
var copyButtonContainer = document.querySelector("#copy-button-container");
var messageContainer = document.querySelector("#message-container");
var copyButton = document.querySelector("#copy-button");
var outputContainer = document.querySelector("#output-container");
var resultsElement = document.querySelector("#results-element");

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function createParagraphs() {
  if (numberInput.value <= 10) {
    checkGenre();
    resultsElement.textContent = "";
    let numberOfParagraphs = Number(numberInput.value);
    copyButtonContainer.textContent = "";
    resultsElement.textContent = " ";
    var copyButton = document.createElement("img");
    copyButton.id = "copy-button";
    copyButton.src = copyButtonSource;
    copyButtonContainer.style.backgroundColor = textBackground;
    copyButton.addEventListener("click", copyParagraphsToClipboard);

    copyButtonContainer.appendChild(copyButton);

    for (
      let paragraphIndex = 0;
      paragraphIndex < numberOfParagraphs;
      paragraphIndex++
    ) {
      makePElement();
    }
  } else if (numberInput.value > 10 && genreSelect.value !== "null") {
    var submitLessMessage = document.createElement("p");
    submitLessMessage.textContent =
      "Please request 10 or fewer paragraphs at a time";
    submitLessMessage.style.color = submitLessMessageText;
    submitLessMessage.id = "submit-fewer";
    inputContainer.appendChild(submitLessMessage);
    setTimeout(() => {
      inputContainer.removeChild(submitLessMessage);
    }, 2000);
  }
}

function makePElement() {
  checkGenre();
  numberOfSentences = getRandomInt(4, 8);
  const pElement = document.createElement("p");
  newSentenceArray = [];
  let sentenceIndex = 0;
  function loopThroughSentences() {
    if (sentenceIndex === 0) {
      var tabBreak = document.createElement("span");
      tabBreak.id = "tab-span";
      pElement.appendChild(tabBreak);
      generateNextSentence();
      sentenceIndex++;
      loopThroughSentences();
    } else if (sentenceIndex < numberOfSentences && sentenceIndex > 0) {
      generateNextSentence();
      sentenceIndex++;
      loopThroughSentences();
    } else if (sentenceIndex === numberOfSentences) {
      outputContainer.appendChild(resultsElement);
    }
  }

  function generateNextSentence() {
    lengthOfSentence = getRandomInt(6, 25);

    wordIndex = getRandomInt(0, genreChosen.length - 1);
    firstWord =
      genreChosen[wordIndex].charAt(0).toUpperCase() +
      genreChosen[wordIndex].slice(1);
    newSentenceArray.push(firstWord);

    for (i = 0; i < lengthOfSentence; i++) {
      wordIndex = getRandomInt(0, genreChosen.length - 1);
      newSentenceArray.push(genreChosen[wordIndex]);
    }

    var newSentenceText = newSentenceArray.join(" ");
    var sentence = document.createElement("span");
    sentence.textContent = newSentenceText;
    pElement.appendChild(sentence);

    var period = document.createElement("span");
    period.textContent = ". ";
    pElement.appendChild(period);

    newSentenceArray = [];
  }
  loopThroughSentences();
  resultsElement.appendChild(pElement);
  pElement.style.color = textColor;

  outputContainer.appendChild(resultsElement);
}

function checkGenre() {
  if (genreSelect.value === "black-metal") {
    genreChosen = blackMetalWords;
    pageBackgroundColor = "var(--blackMetalBackground)";
    textBackground = "var(--blackMetalTextBackground)";
    borderColor = "5px solid var(--blackMetalBorder)";
    titleBackground = "var(--blackMetalTitleBackground)";
    titleTextColor = "var(--blackMetalTitleText)";
    boxShadowColor = "3px 3px 3px var(--blackMetalBoxShadow)";
    genreSelectBackground = "var(--blackMetalGenreSelectBackground)";
    genreSelectText = "var(--blackMetalGenreSelectText)";
    buttonBackground = "var(--blackMetalButtonBackground)";
    buttonText = "var(--blackMetalButtonText)";
    textColor = "white";
    titleText.textContent = "Lorem Ipsummon";
    tabText.textContent = "Lorem Ipsummon";
    descriptionText =
      "Generate placeholder text of the most common words used in Black Metal lyrics";
    messageElementText = "white";
    messageElementBorder = "3px solid white";
    submitLessMessageText = "white";
    favIcon.href = "./icons/metalicon.png";
    copyButtonSource = "./icons/copypasteblack.png";
  } else if (genreSelect.value === "indie") {
    genreChosen = indieWords;
    pageBackgroundColor = "var(--indieBackground)";
    textBackground = "var(--indieTextBackground)";
    borderColor = "5px solid var(--indieBorder)";
    titleBackground = "var(--indieTitleBackground)";
    titleTextColor = "var(--indieTitleText)";
    boxShadowColor = "3px 3px 3px var(--indieBoxShadow)";
    genreSelectBackground = "var(--indieGenreSelectBackground)";
    genreSelectText = "var(--indieGenreSelectText)";
    buttonBackground = "var(--indieButtonBackground)";
    buttonText = "var(--indieButtonText)";
    textColor = "black";
    titleText.textContent = "Lorem Indiesum";
    tabText.textContent = "Lorem Indiesum";
    descriptionText =
      "Generate placeholder text of the most common words used in Indie Rock lyrics";
    messageElementText = "black";
    messageElementBorder = "3px solid black";
    submitLessMessageText = "black";
    favIcon.href = "./icons/indieicon.png";
    copyButtonSource = "./icons/copypaste.png";
  } else if (genreSelect.value === "rap") {
    genreChosen = rapWords;
    pageBackgroundColor = "var(--rapBackground)";
    textBackground = "var(--rapTextBackground)";
    borderColor = "5px solid var(--rapBorder)";
    titleBackground = "var(--rapTitleBackground)";
    titleTextColor = "var(--rapTitleText)";
    boxShadowColor = "10px 5px 5px var(--rapBoxShadow)";
    genreSelectBackground = "var(--rapGenreSelectBackground)";
    genreSelectText = "var(--rapGenreSelectText)";
    buttonBackground = "var(--rapButtonBackground)";
    buttonText = "var(--rapButtonText)";
    textColor = "black";
    tabText.textContent = "Lorap Ipson";
    titleText.textContent = "Lorap Ipson";
    descriptionText =
      "Generate placeholder text of the most common words used in Rap lyrics";
    messageElementText = "black";
    messageElementBorder = "3px solid black";
    submitLessMessageText = "black";
    favIcon.href = "./icons/rapicon.png";
    copyButtonSource = "./icons/copypaste.png";
  } else if (genreSelect.value === "country") {
    genreChosen = countryWords;
    pageBackgroundColor = "var(--countryBackground)";
    textBackground = "var(--countryTextBackground)";
    borderColor = "5px solid var(--countryBorder)";
    titleBackground = "var(--countryTitleBackground)";
    titleTextColor = "var(--countryTitleText)";
    boxShadowColor = "3px 3px 3px var(--countryBoxShadow)";
    genreSelectBackground = "var(--countryGenreSelectBackground)";
    genreSelectText = "var(--countryGenreSelectText)";
    buttonBackground = "var(--countryButtonBackground)";
    buttonText = "var(--countryButtonText)";
    textColor = "black";
    titleText.textContent = "Lonesome Ipso";
    tabText.textContent = "Lonesome Ipso";
    descriptionText =
      "Generate placeholder text of the most common words used in Country lyrics";
    messageElementText = "black";
    messageElementBorder = "3px solid black";
    submitLessMessageText = "black";
    favIcon.href = "./icons/countryicon.png";
    copyButtonSource = "./icons/copypaste.png";
  }
}

async function copyParagraphsToClipboard() {
  try {
    const paragraphs = Array.from(document.querySelectorAll("p"));
    const paragraphsText = paragraphs
      .map((p) => p.textContent.trim())
      .join("\n\n");
    await navigator.clipboard.writeText(paragraphsText);
    displayMessage("Text successfully copied");
  } catch (err) {
    console.error("Failed to copy: ", err);
  }
}

function displayMessage(message, isError = false) {
  const messageElement = document.createElement("div");
  messageElement.id = "message-element";
  messageElement.style.color = messageElementText;
  messageElement.style.border = messageElementBorder;
  messageElement.textContent = message;
  messageElement.className = isError ? "error-message" : "success-message";
  copyButtonContainer.appendChild(messageElement);

  setTimeout(() => {
    copyButtonContainer.removeChild(messageElement);
  }, 1000);
}

function changeTheme() {
  checkGenre();
  resultsElement.textContent = "";
  outputContainer.textContent = "";
  copyButtonContainer.textContent = "";
  outputContainer.style.backgroundColor = textBackground;
  copyButtonContainer.style.backgroundColor = textBackground;
  descrptionLine.style.color = textColor;
  descrptionLine.textContent = descriptionText;
  titleText.style.backgroundColor = titleBackground;
  titleText.style.color = titleTextColor;
  titleText.style.boxShadow = boxShadowColor;
  genreSelect.style.backgroundColor = genreSelectBackground;
  genreSelect.style.color = genreSelectText;
  submitButton.style.backgroundColor = buttonBackground;
  submitButton.style.color = buttonText;
  container.style.border = borderColor;
  container.style.backgroundColor = textBackground;
  everything.style.backgroundColor = pageBackgroundColor;
}

function checkForGenreSelected() {
  if (genreSelect.value) {
    createParagraphs();
  } else {
    var selectGenreMessage = document.createElement("p");
    selectGenreMessage.textContent = "Please select a genre";
    selectGenreMessage.id = "submit-fewer";
    inputContainer.appendChild(selectGenreMessage);
    setTimeout(() => {
      inputContainer.removeChild(selectGenreMessage);
    }, 2000);
  }
}

submitButton.addEventListener("click", checkForGenreSelected);
